twig:
  default_path: '%kernel.project_dir%/templates'
  form_theme: 'bootstrap_5_layout.html.twig'
  globals:
    app_images_wish_directory: 'uploads/images/profil'

when@test:
  twig:
    strict_variables: true
